# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/node:latest

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

  working_directory: ~/repo
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
                root: .
                paths:
                  - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      # run tests!
      - run: npm run build-dev
      - run: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .
  audit:
      <<: *defaults
      steps:
        - attach_workspace:
            # Must be absolute path or relative path from working_directory
            at: ~/repo

        # run tests!
        - run: npm audit
  deploy-dev:
      docker:
          # specify the version you desire here
          - image: cibuilds/aws
      working_directory: ~/repo

      steps:
        - attach_workspace:
            at: ~/repo
        - run: npm run build-dev
        - run: aws s3 sync public/ s3://dev-employee-client


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - audit:
          requires:
            - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: master

